#!/sbin/perl

$FILENAME = ".dree";

$ls_c = "ls -A";
$ls = `$ls_c`;

print $ls
@contents = split(" ", $ls);
$content_size = scalar(@contents);

$folders_c = "ls -d */ .*/";
$folders = `$folders_c`;

@folders = split(" ", $folders);
$folders_size = scalar(@folders);

# Create .dree
open(my $fdree, '>', $FILENAME) or die "Couldn't open file";
for($i = 2; $i < $folders_size; $i++){
    print $fdree @folders[$i], "\n";
}

close $fdree;
print "done\n";
