#!/sbin/perl

$ls_c = "ls -A";
$ls = `$ls_c`;

print $ls
@contents = split(" ", $ls);
$content_size = scalar(@contents);

for($i = 0; $i < $content_size; $i++){
    print @contents[$i], "\n";
}

$folders_c = "ls -d */ .*/";
$folders = `$folders_c`;

@folders = split(" ", $folders);
$folders_size = scalar(@folders);

for($i = 0; $i < $folders_size; $i++){
    print @folders[$i], "\n";
}
